name = "club-futbol-api"
main = "src/index.js"
compatibility_date = "2026-09-01"

# [[r2_buckets]]
# binding = "FILES"
# bucket_name = "club-futbol-files"

# wrangler secret put DATABASE_URL
# wrangler secret put ADMIN_TOKEN
